# Pythonによる記述統計: 1変量データ

In [1]:
import numpy as np
import scipy as sp

In [10]:
# 表示される小数点以下の桁数を設定
%precision 3

'%.3f'

## 1変量データの管理

魚の体調だけ、と行ったように、１種類しかないデータを１変量データと呼ぶ.

１変量データを扱う場合は、numpyアレイを使うのが簡単。

In [11]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

## 合計とサンプルサイズ

In [12]:
sp.sum(fish_data)

40

In [13]:
len(fish_data)

10

## 平均値（期待値）

In [14]:
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.0

In [16]:
sp.mean(fish_data) # mean関数を使うと簡単に求めることができる

4.0

## 標本分散

In [17]:
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.2

In [19]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [20]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [21]:
(fish_data - mu) **2

array([4., 1., 1., 0., 0., 0., 0., 1., 1., 4.])

In [22]:
sp.sum((fish_data - mu) ** 2)

12.0

In [23]:
# こちらもvar関数を使うと簡単に計算できる
sp.var(fish_data)

1.2

## 不偏分散